=== Pmuzik/gamecat/gamecat_1_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://pmuzik.github.io/gamecat/1.0"
  xmlns="http://pmuzik.github.io/gamecat/1.0"
  elementFormDefault="qualified">

<!-- Root element -->
  <xs:element name="game">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="titles" type="titlesType"/>
        <xs:element name="developer" type="authorityStringType"/>
        <xs:element name="publisher" type="authorityStringType"/>
        <xs:element name="platform" type="xs:string"/>
        <xs:element name="genre" type="xs:string"/>
        <xs:element name="players" type="xs:string"/>
        <xs:element name="releases" type="releasesType"/>
        <xs:element name="credits" type="creditsType"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

<!-- Named type definitions -->
  <xs:complexType name="authorityStringType">
      <xs:simpleContent>
          <xs:extension base="xs:string">
              <xs:attribute name="authority-uri" type="xs:anyURI" use="optional"/>
              <xs:attribute name="authority-source" type="xs:string" use="optional"/>
              <xs:attribute name="authority-verified" type="xs:boolean" use="optional"/>
          </xs:extension>
      </xs:simpleContent>
  </xs:complexType>
  
  <xs:complexType name="titlesType">
      <xs:sequence>
          <xs:element name="title" maxOccurs="unbounded">
              <xs:complexType>
                  <xs:simpleContent>
                      <xs:extension base="xs:string">
                          <xs:attribute name="type" use="required">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:enumeration value="primary"/>
                                      <xs:enumeration value="localized"/>
                                      <xs:enumeration value="variant"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:attribute>
                          <xs:attribute name="lang" type="xs:language" use="required"/>
                          <xs:attribute name="script" use="optional">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:enumeration value="Latn"/>
                                      <xs:enumeration value="Jpan"/>
                                      <xs:enumeration value="Cyrl"/>
                                      <xs:enumeration value="Hans"/>
                                      <xs:enumeration value="Hant"/>
                                      <xs:enumeration value="Kore"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:attribute>
                      </xs:extension>
                  </xs:simpleContent>
              </xs:complexType>
          </xs:element>
      </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="releasesType">
      <xs:sequence>
          <xs:element name="release" maxOccurs="unbounded">
              <xs:complexType>
                  <xs:sequence>
                      <xs:element name="date" type="xs:date"/>
                      <xs:element name="region" type="xs:string"/>
                  </xs:sequence>
              </xs:complexType>
          </xs:element>
      </xs:sequence>
  </xs:complexType>
  
  <xs:complexType name="creditsType">
      <xs:sequence>
          <xs:element name="credit" maxOccurs="unbounded">
              <xs:complexType>
                  <xs:simpleContent>
                      <xs:extension base="authorityStringType">
                          <xs:attribute name="role" use="required">
                              <xs:simpleType>
                                  <xs:restriction base="xs:string">
                                      <xs:enumeration value="director"/>
                                      <xs:enumeration value="designer"/>
                                      <xs:enumeration value="composer"/>
                                      <xs:enumeration value="programmer"/>
                                      <xs:enumeration value="artist"/>
                                      <xs:enumeration value="writer"/>
                                      <xs:enumeration value="producer"/>
                                      <xs:enumeration value="planner"/>
                                  </xs:restriction>
                              </xs:simpleType>
                          </xs:attribute>
                      </xs:extension>
                  </xs:simpleContent>
              </xs:complexType>
          </xs:element>
      </xs:sequence>
  </xs:complexType>
  
</xs:schema>

=== Pmuzik/gamecat/saga00.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="https://pmuzik.github.io/gamecat/gamecat.xsl"?>
<game xmlns="http://pmuzik.github.io/gamecat/"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="http://github.com/Pmuzik/gamecat/gamecat_1_0.xsd">

  <titles>
    <title type="primary" lang="ja" script="Latn">Makai Toushi SaGa</title>
    <title type="primary" lang="ja" script="Jpan">魔界塔士Sa·Ga</title>
    <title type="localized" lang="en">Final Fantasy Legend</title>
  </titles>

  <developer authority-uri="https://www.wikidata.org/wiki/Q739552"
    authority-source="wikidata">Square</developer>
  <publisher authority-uri="https://www.wikidata.org/wiki/Q739552"
    authority-source="wikidata">Square</publisher>

  <platform>Game Boy</platform>
  <genre>Role-playing game</genre>
  <players>Single-player</players>

  <releases>
    <release>
      <date>1989-12-15</date>
      <region>Japan</region>
    </release>
    <release>
      <date>1990-09-30</date>
      <region>North America</region>
    </release>
  </releases>

  <credits>
    <credit role="director"
        authority-uri="https://www.wikidata.org/wiki/Q419404"
        authority-source="wikidata">Kawazu, Akitoshi</credit>
    <credit role="designer"
        authority-uri="https://www.wikidata.org/wiki/Q419404"
        authority-source="wikidata">Kawazu, Akitoshi</credit>
    <credit role="composer"
        authority-uri="https://www.wikidata.org/wiki/Q312327"
        authority-source="wikidata">Uematsu, Nobuo</credit>
    <credit role="programmer"
        authority-verified="false">Oki, Takashi</credit>
    <credit role="programmer"
        authority-verified="false">Okabe, Naoki</credit>
    <credit role="artist"
        authority-verified="false">Tanaka, Ryoko</credit>
    <credit role="artist"
        authority-uri="https://www.wikidata.org/wiki/Q2657029"
        authority-source="wikidata">Tokita, Takashi</credit>
    <credit role="writer"
        authority-uri="https://www.wikidata.org/wiki/Q419404"
        authority-source="wikidata">Kawazu, Akitoshi</credit>
  </credits>

</game>
